#ifndef BASEDEFINE_TYPE_CONVERT_H
#define BASEDEFINE_TYPE_CONVERT_H
#include "types.h"

#ifdef __cplusplus

template <typename to, typename from>
to sge_safe_convert(from f);

#endif
SGE_EXTERN_C_START
#define DECL_SAFE_CONVERT(to, from)\
sge_##to sge_safe_convert_##from##_to_##to(sge_##from f);
DECL_SAFE_CONVERT(int8, int16)
DECL_SAFE_CONVERT(int8, int32)
DECL_SAFE_CONVERT(int8, int64)
DECL_SAFE_CONVERT(int8, uint8)
DECL_SAFE_CONVERT(int8, uint16)
DECL_SAFE_CONVERT(int8, uint32)
DECL_SAFE_CONVERT(int8, uint64)

DECL_SAFE_CONVERT(int16, int32)
DECL_SAFE_CONVERT(int16, int64)
DECL_SAFE_CONVERT(int16, uint16)
DECL_SAFE_CONVERT(int16, uint32)
DECL_SAFE_CONVERT(int16, uint64)

DECL_SAFE_CONVERT(int32, int64)
DECL_SAFE_CONVERT(int32, uint32)
DECL_SAFE_CONVERT(int32, uint64)

DECL_SAFE_CONVERT(int64, uint64)

DECL_SAFE_CONVERT(uint8, uint16)
DECL_SAFE_CONVERT(uint8, uint32)
DECL_SAFE_CONVERT(uint8, uint64)
DECL_SAFE_CONVERT(uint8, int8)
DECL_SAFE_CONVERT(uint8, int16)
DECL_SAFE_CONVERT(uint8, int32)
DECL_SAFE_CONVERT(uint8, int64)

DECL_SAFE_CONVERT(uint16, uint32)
DECL_SAFE_CONVERT(uint16, uint64)
DECL_SAFE_CONVERT(uint16, int8)
DECL_SAFE_CONVERT(uint16, int16)
DECL_SAFE_CONVERT(uint16, int32)
DECL_SAFE_CONVERT(uint16, int64)

DECL_SAFE_CONVERT(uint32, uint64)
DECL_SAFE_CONVERT(uint32, int8)
DECL_SAFE_CONVERT(uint32, int16)
DECL_SAFE_CONVERT(uint32, int32)
DECL_SAFE_CONVERT(uint32, int64)

DECL_SAFE_CONVERT(uint64, int8)
DECL_SAFE_CONVERT(uint64, int16)
DECL_SAFE_CONVERT(uint64, int32)
DECL_SAFE_CONVERT(uint64, int64)

SGE_EXTERN_C_END
#endif
